apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
    - host: "40.121.184.65.nip.io"  # Updated from localhost to the nip.io domain
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8082
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8082
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8082
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8082
          - path: /config
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8082
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8082
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
