apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: salimbouazizi/formation-frontend:0.0.6 # Replace with your actual image
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
  annotations:
    #service.beta.kubernetes.io/azure-pip-name: my-static-ip
    #service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_rg-aks-demoo_aks-demo_eastus
spec:
  selector:
    app: react-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Optional: Specify a port in the range 30000–32767; Kubernetes assigns one if omitted
  type: NodePort
