apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15
          command: ['sh', '-c', 'sleep 10; until pg_isready -h postgres-service -p 5432 -U postgres; do echo waiting for postgres; sleep 2; done;']
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: SPRING_DATASOURCE_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      containers:
        - name: backend
          image: salimbouazizi/formation-backend:0.0.1  # Replace with your actual image
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20  # Moved comment to a new line
            # Triggered by Jenkins at 06 سبتمبر, 2025 CET 05:25:50 م
